[profile.default]
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 999
evm_version = "cancun"
ast = true

[fuzz]
runs = 1_000
max_test_rejects = 1_000_000

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
