[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@account-abstraction-v6/=lib/account-abstraction-v6/contracts/",
    "@account-abstraction-v7/=lib/account-abstraction-v7/contracts/",
    "@forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
