[profile.default]
via_ir = true
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1000000
ast = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
